// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.
// Source: input.di.ts
// Generator: clean-di-codegen 1.0.0
// Hash: sha256:6c7f6e84452e7818f82e203f97aa49e0a7f642d96cb61213377c4e66d808246b

import { createContext } from "clean-di/runtime";
import { Logger } from "./Logger";
import { commentsConfig } from "./commentsConfig";
import { HttpCommentsRepository } from "./HttpCommentsRepository.js";
import { ListCommentsUseCase } from "./ListCommentsUseCase.js";

export const blogContext = createContext<void, { listComments: ListCommentsUseCase }>((cfg) => {
  const logger = new Logger();
  const commentsRepository = new HttpCommentsRepository(logger);
  const listComments = new ListCommentsUseCase(commentsRepository);

  return {
    bag: { logger, commentsRepository, listComments },
    expose: { listComments },
  };
});
