// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.
// Source: CalcContext.di.ts
// Generator: clean-di-codegen 1.0.0
// Hash: sha256:729d7e40701090cba53f69973507a45605fa459ab5a534bc4c1437b5a1583e11

import { createContext } from "clean-di/runtime";
import { Calculator } from "./Calculator.js";
import { type MathConfig } from "./MathConfig.js";
import { mathConfig } from "./mathConfig.di.js";
import { Adder } from "./Adder.js";
import { Multiplier } from "./Multiplier.js";

export const calcContext = createContext<MathConfig, { calculator: Calculator }>(
  (cfg) => {
    const precision = cfg.precision;
    const adder = new Adder(precision);
    const multiplier = new Multiplier(precision);
    const calculator = new Calculator(adder, multiplier);

    return {
      bag: { precision, adder, multiplier, calculator },
      expose: { calculator },
    };
  },
);
