// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.
// Source: CalcContext.di.ts
// Generator: clean-di-codegen 0.0.0
// Hash: sha256:a9c74289a71d7a787fe12b6096e7211f71355c2af3bad2e136775a414642182e

import { createContext } from "clean-di/runtime";
import { type MathConfig } from "./MathConfig.js";
import { mathConfig } from "./mathConfig.di.js";
import { Calculator } from "./Calculator.js";
import { Adder } from "./Adder.js";
import { Multiplier } from "./Multiplier.js";

export const calcContext = createContext<MathConfig, { calculator: Calculator }>(
  (cfg) => {
    const precision = cfg.precision;
    const adder = new Adder(precision);
    const multiplier = new Multiplier(precision);
    const calculator = new Calculator(adder, multiplier);

    return {
      bag: { precision, adder, multiplier, calculator },
      expose: { calculator },
    };
  },
);
