// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.
// Source: input.di.ts
// Generator: clean-di-codegen 1.0.0
// Hash: sha256:77a87dd84ea4fdbaf93ab2ea7b1138745235ae8cbbace12e35a8e0c91ba1d214

import { createContext } from "clean-di/runtime";
import { Greeter } from "./Greeter";
import { helperConfig } from "./helperConfig";
import { Logger } from "./Logger.js";

export const appContext = createContext<void, { greeter: Greeter }>(
  (cfg) => {
    const logger = new Logger();
    const greeter = new Greeter(logger);

    return {
      bag: { logger, greeter },
      expose: { greeter },
      postConstruct: (cfg) => {
        (({ logger }: { logger: Logger }) => {
    logger.log("helper:postConstruct");
  })({ logger, greeter });
        (({ greeter }: { greeter: Greeter }) => {
    greeter.greet("world");
  })({ logger, greeter });
      },
      preDestroy: (cfg) => {
        (({ greeter }: { greeter: Greeter }) => {
    greeter.logger.log("app:preDestroy");
  })({ logger, greeter });
        (({ logger }: { logger: Logger }) => {
    logger.log("helper:preDestroy");
  })({ logger, greeter });
      },
    };
  },
);
