// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.
// Source: input.di.ts
// Generator: clean-di-codegen 1.0.0
// Hash: sha256:1d2bc11e018273c201b14c36406fa0701f6163e7f80cca3369a5ad9311296e21

import { createContext } from "clean-di/runtime";
import { HttpPostsRepository } from "./HttpPostsRepository";
import { ListPostsUseCase } from "./ListPostsUseCase";
import { Logger } from "./Logger";
import { type PostsContextConfig } from "./input.di.js";

export const postsContext = createContext<PostsContextConfig, { listPosts: ListPostsUseCase }>(
  (cfg) => {
    const apiBaseUrl = cfg.apiBaseUrl;
    const logger = new Logger();
    const postsRepository = new HttpPostsRepository(apiBaseUrl, logger);
    const listPosts = new ListPostsUseCase(postsRepository);

    return {
      bag: { apiBaseUrl, logger, postsRepository, listPosts },
      expose: { listPosts },
    };
  },
);
