// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.
// Source: input.di.ts
// Generator: clean-di-codegen 1.0.0
// Hash: sha256:83c7f19e2b1b3f77b84c120aed694c6a9e667645bb4da0f153e8e5812d48446a

import { createContext } from "clean-di/runtime";
import { Logger } from "./Logger";
import { HttpPostsRepository } from "./HttpPostsRepository";
import { ListPostsUseCase } from "./ListPostsUseCase";

export const postsContext = createContext<PostsContextConfig, { listPosts: unknown }>(
  (cfg) => {
    const apiBaseUrl = cfg.apiBaseUrl;
    const logger = new Logger();
    const postsRepository = new HttpPostsRepository(apiBaseUrl, logger);
    const listPosts = new ListPostsUseCase(postsRepository);

    return {
      bag: { apiBaseUrl, logger, postsRepository, listPosts },
      expose: { listPosts },
    };
  },
);
