// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.
// Source: input.di.ts
// Generator: clean-di-codegen 1.0.0
// Hash: sha256:d9f43e384242e192a556ba1fe3046dc8b0747d3d7ca48c6f5b4ead957bcdb9ed

import { createContext } from "clean-di/runtime";
import { Logger } from "./Logger";
import { Greeter } from "./Greeter";

export const greeterContext = createContext<void, { greeter: Greeter }>(
  (cfg) => {
    const logger = new Logger();
    const greeter = new Greeter(logger);

    return {
      bag: { logger, greeter },
      expose: { greeter },
      postConstruct: (cfg) => (({ greeter }) => {
    greeter.init();
  })({ logger, greeter }),
      preDestroy: (cfg) => (({ greeter }) => {
    greeter.dispose();
  })({ logger, greeter }),
    };
  },
);
