// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.
// Source: input.di.ts
// Generator: clean-di-codegen 1.0.0
// Hash: sha256:04b7c0763c4b9da1b5b115ff05221f526f3aabdf3d48a52f210a9317e7c22053

import { createContext } from "clean-di/runtime";
import { Greeter } from "./Greeter";
import { Logger } from "./Logger";

export const greeterContext = createContext<void, { greeter: Greeter }>((cfg) => {
  const logger = new Logger();
  const greeter = new Greeter(logger);

  return {
    bag: { logger, greeter },
    expose: { greeter },
    postConstruct: (cfg) =>
      (({ greeter }) => {
        greeter.init();
      })({ logger, greeter }),
    preDestroy: (cfg) =>
      (({ greeter }) => {
        greeter.dispose();
      })({ logger, greeter }),
  };
});
