// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.
// Source: GreeterContext.di.ts
// Generator: clean-di-codegen 0.0.0
// Hash: sha256:017d46c1a9daed478473661ffcba15fbe67842dbc39df8b7572e1ec5a6659321

import { createContext } from "clean-di/runtime";
import { type AppConfig } from "./AppConfig.js";
import { Logger } from "./Logger.js";
import { Greeter } from "./Greeter.js";

export const greeterContext = createContext<AppConfig, { greeter: Greeter }>(
  (cfg) => {
    const name = cfg.name;
    const logger = new Logger();
    const greeter = new Greeter(logger, name);

    return {
      bag: { name, logger, greeter },
      expose: { greeter },
    };
  },
);
