// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.
// Source: GreeterContext.di.ts
// Generator: clean-di-codegen 1.0.0
// Hash: sha256:89f7f1b23d812aeec4a27fda3cad166206208b73f32e9c78c25f1e36f6a7ab30

import { createContext } from "clean-di/runtime";
import { type AppConfig } from "./AppConfig.js";
import { Greeter } from "./Greeter.js";
import { Logger } from "./Logger.js";

export const greeterContext = createContext<AppConfig, { greeter: Greeter }>(
  (cfg) => {
    const name = cfg.name;
    const logger = new Logger();
    const greeter = new Greeter(logger, name);

    return {
      bag: { name, logger, greeter },
      expose: { greeter },
    };
  },
);
