// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.
// Source: GreeterContext.di.ts
// Generator: clean-di-codegen 0.0.0
// Hash: sha256:013d74874fc457493dc3934bea114f706326206ab543c6cd4f575bd8dc2f42c6

import { createContext } from "clean-di/runtime";
import { type AppConfig } from "./AppConfig.js";
import { Logger } from "./Logger.js";
import { Greeter } from "./Greeter.js";

export const greeterContext = createContext<AppConfig, { greeter: Greeter }>(
  (cfg) => {
    const name = cfg.name;
    const logger = new Logger();
    const greeter = new Greeter(logger, name);

    return {
      bag: { name, logger, greeter },
      expose: { greeter },
    };
  },
);
