/**
 * rollup.integration.test.ts — T-099
 *
 * Runs a real programmatic rollup build against a temp-dir fixture project
 * with the real `cleanDiRollupPlugin` (no mocks). Asserts that the plugin's
 * `buildStart` hook actually invokes codegen and emits `.di.generated.ts`
 * next to the source `.di.ts`, and that codegen failures abort the rollup
 * build.
 */
import { readFile, rm, stat } from "node:fs/promises";
import { join } from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { cleanDiRollupPlugin } from "../../src/plugins/rollup";

import { createTempProject, UNAMBIGUOUS_FIXTURE, UNRESOLVABLE_FIXTURE } from "./fixtures";

describe("cleanDiRollupPlugin — real rollup build", () => {
  let projectDir: string | undefined;

  beforeEach(() => {
    projectDir = undefined;
  });

  afterEach(async () => {
    if (projectDir !== undefined) {
      await rm(projectDir, { recursive: true, force: true });
      projectDir = undefined;
    }
  });

  it("emits .di.generated.ts next to the source .di.ts during a real rollup build", async () => {
    projectDir = await createTempProject({
      files: [
        ...UNAMBIGUOUS_FIXTURE.files,
        // Minimal JS entry: rollup has no TS support of its own, so we hand
        // it a plain JS file. The bundle output is not asserted; we only
        // care that buildStart fires the codegen.
        { relativePath: "entry.js", contents: "export const ok = true;\n" },
      ],
    });

    const { rollup } = await import("rollup");

    const bundle = await rollup({
      input: join(projectDir, "entry.js"),
      plugins: [cleanDiRollupPlugin({ cwd: projectDir })],
      // Silence rollup's "no name was provided" warnings etc.
      onwarn: () => {},
    });

    try {
      // Generate (but don't write) to make sure the full pipeline runs.
      await bundle.generate({ format: "esm" });
    } finally {
      await bundle.close();
    }

    const generatedPath = join(projectDir, "input.di.generated.ts");
    const generatedStat = await stat(generatedPath);
    expect(generatedStat.isFile()).toBe(true);

    const generatedSource = await readFile(generatedPath, "utf8");
    expect(generatedSource).toContain("// AUTO-GENERATED by clean-di-codegen");
    expect(generatedSource).toContain('from "clean-di/runtime"');
    expect(generatedSource).toContain("export const postsContext");
    expect(generatedSource).toContain("new ListPostsUseCase(postsRepository)");
  }, 30_000);

  it("fails the rollup build with a meaningful error when codegen reports CDI-001", async () => {
    projectDir = await createTempProject({
      files: [
        ...UNRESOLVABLE_FIXTURE.files,
        { relativePath: "entry.js", contents: "export const ok = true;\n" },
      ],
    });

    const { rollup } = await import("rollup");
    const root = projectDir;

    await expect(
      rollup({
        input: join(root, "entry.js"),
        plugins: [cleanDiRollupPlugin({ cwd: root })],
        onwarn: () => {},
      }),
    ).rejects.toThrow(/clean-di codegen failed/);

    // No generated file should have been written for the broken fixture.
    await expect(stat(join(root, "input.di.generated.ts"))).rejects.toMatchObject({
      code: "ENOENT",
    });
  }, 30_000);
});
