/**
 * vite.integration.test.ts — T-099
 *
 * Runs `vite build` against a temp-dir fixture project with the real
 * `cleanDiVitePlugin` (no mocks). Asserts that the plugin's `buildStart` hook
 * actually invokes codegen and emits `.di.generated.ts` next to the source
 * `.di.ts`, and that codegen failures abort the build with a meaningful error.
 *
 * NOTE on `vite dev`: a full integration test for dev mode would need to
 * spin up a Vite dev server, wait for chokidar events to settle, then tear
 * down the server cleanly. That's substantially harder to keep non-flaky in
 * CI and would multiply the runtime of an already-slow test suite. Dev-mode
 * is exercised by the existing mocked unit tests (`configureServer` starts a
 * watcher, `closeBundle` stops it). Wiring an end-to-end dev-server test is
 * deferred until we have a concrete bug or feature that needs it.
 */
import { readFile, rm, stat } from "node:fs/promises";
import { join } from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { cleanDiVitePlugin } from "../../src/plugins/vite";

import { createTempProject, UNAMBIGUOUS_FIXTURE, UNRESOLVABLE_FIXTURE } from "./fixtures";

describe("cleanDiVitePlugin — real vite build", () => {
  let projectDir: string | undefined;

  beforeEach(() => {
    projectDir = undefined;
  });

  afterEach(async () => {
    if (projectDir !== undefined) {
      await rm(projectDir, { recursive: true, force: true });
      projectDir = undefined;
    }
  });

  it("emits .di.generated.ts next to the source .di.ts during a real vite build", async () => {
    projectDir = await createTempProject({
      files: [
        ...UNAMBIGUOUS_FIXTURE.files,
        // Minimal JS entry: avoids needing Vite TS handling. We only care
        // that buildStart fires; the bundle output is not asserted.
        { relativePath: "entry.js", contents: "export const ok = true;\n" },
      ],
    });

    // Import vite lazily so vite's own logger setup doesn't pollute test
    // startup time when running other test files.
    const { build } = await import("vite");

    await build({
      root: projectDir,
      logLevel: "silent",
      plugins: [cleanDiVitePlugin({ cwd: projectDir })],
      build: {
        write: false,
        emptyOutDir: false,
        rollupOptions: { input: join(projectDir, "entry.js") },
      },
    });

    const generatedPath = join(projectDir, "input.di.generated.ts");
    const generatedStat = await stat(generatedPath);
    expect(generatedStat.isFile()).toBe(true);

    const generatedSource = await readFile(generatedPath, "utf8");
    expect(generatedSource).toContain("// AUTO-GENERATED by clean-di-codegen");
    expect(generatedSource).toContain('from "clean-di/runtime"');
    expect(generatedSource).toContain("export const postsContext");
    expect(generatedSource).toContain("new ListPostsUseCase(postsRepository)");
  }, 30_000);

  it("fails the vite build with a meaningful error when codegen reports CDI-001", async () => {
    projectDir = await createTempProject({
      files: [
        ...UNRESOLVABLE_FIXTURE.files,
        { relativePath: "entry.js", contents: "export const ok = true;\n" },
      ],
    });

    const { build } = await import("vite");
    const root = projectDir;

    await expect(
      build({
        root,
        logLevel: "silent",
        plugins: [cleanDiVitePlugin({ cwd: root })],
        build: {
          write: false,
          emptyOutDir: false,
          rollupOptions: { input: join(root, "entry.js") },
        },
      }),
    ).rejects.toThrow(/clean-di codegen failed/);

    // No generated file should have been written for the broken fixture.
    await expect(stat(join(root, "input.di.generated.ts"))).rejects.toMatchObject({
      code: "ENOENT",
    });
  }, 30_000);
});
