// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.
// Source: input.di.ts
// Generator: clean-di-codegen 1.0.0
// Hash: sha256:affddbdf910923f7e2b684bab0d395d6787938f6d207459664e49e804680d00b

import { createContext } from "clean-di/runtime";
import { aConfig } from "./aConfig";
import { bConfig } from "./bConfig";

export const appContext = createContext<void, { serviceA: ServiceA, serviceB: ServiceB }>(
  (cfg) => {
    const logger = new Logger();
    const serviceA = new ServiceA(logger);
    const serviceB = new ServiceB(logger);

    return {
      bag: { logger, serviceA, serviceB },
      expose: { serviceA, serviceB },
    };
  },
);
