// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.
// Source: SampleContext.di.ts (synthetic — hand-written for the runtime tracer)
// Generator: hand-written (T-025 fixture; pre-codegen)

import { createContext } from "../../../src/runtime/createContext";

export class Logger {
  public messages: string[] = [];

  public log(msg: string): void {
    this.messages.push(msg);
  }
}

export class Counter {
  public value = 0;

  public increment(): void {
    this.value += 1;
  }
}

export class Greeter {
  public initialized = false;
  public disposed = false;

  public constructor(
    public readonly logger: Logger,
    public readonly counter: Counter,
  ) {}

  public init(): void {
    this.initialized = true;
    this.logger.log("Greeter init");
    this.counter.increment();
  }

  public dispose(): void {
    this.disposed = true;
    this.logger.log("Greeter dispose");
  }

  public greet(name: string): string {
    return `hello, ${name} (#${this.counter.value})`;
  }
}

export interface SampleConfig {
  readonly prefix: string;
}

export interface SampleExposed {
  readonly greeter: Greeter;
  readonly counter: Counter;
}

export const sampleContext = createContext<SampleConfig, SampleExposed>((cfg) => {
  const logger = new Logger();
  logger.log(`build start prefix=${cfg.prefix}`);

  const counter = new Counter();
  const greeter = new Greeter(logger, counter);

  return {
    bag: { logger, counter, greeter },
    expose: { greeter, counter },
    postConstruct: () => {
      greeter.init();
    },
    preDestroy: () => {
      greeter.dispose();
    },
  };
});
