// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.
// Source: input.di.ts
// Generator: clean-di-codegen 1.0.0
// Hash: sha256:2714b502602ceaed580497299fd0bee3453f848f339b1b02c7419008c62cebb4

import { createContext } from "clean-di/runtime";
import { Logger } from "./Logger";
import { Greeter } from "./Greeter";

export const greeterContext = createContext<GreeterConfig, { greeter: Greeter }>(
  (cfg) => {
    const prefix = cfg.prefix;
    const logger = new Logger();
    const greeter = new Greeter(prefix, logger);

    return {
      bag: { prefix, logger, greeter },
      expose: { greeter },
    };
  },
);
