// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.
// Source: input.di.ts
// Generator: clean-di-codegen 1.0.0
// Hash: sha256:04c610fd833d9cc7e9591c3308d9555f5aab675d4cb5c782eb4f0543d0ced592

import { createContext } from "clean-di/runtime";
import { Greeter } from "./Greeter";
import { Logger } from "./Logger";

export const greeterContext = createContext<GreeterConfig, { greeter: Greeter }>((cfg) => {
  const prefix = cfg.prefix;
  const logger = new Logger();
  const greeter = new Greeter(prefix, logger);

  return {
    bag: { prefix, logger, greeter },
    expose: { greeter },
  };
});
