// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.
// Source: input.di.ts
// Generator: clean-di-codegen 1.0.0
// Hash: sha256:be9d5ffa8edf973ceef1731f7f23fa437ad7b2c745772c1cdc19577f685b51d9

import { createContext } from "clean-di/runtime";
import { Greeter } from "./Greeter";
import { Logger } from "./Logger";
import { Orphan } from "./Orphan";

export const ctx = createContext<void, { greeter: Greeter }>(
  (cfg) => {
    const logger = new Logger();
    const greeter = new Greeter(logger);
    const orphan = new Orphan();

    return {
      bag: { logger, greeter, orphan },
      expose: { greeter },
    };
  },
);
