// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.
// Source: input.di.ts
// Generator: clean-di-codegen 1.0.0
// Hash: sha256:95365d76751088175bbaa4d0afebab7e4bb568f63479a38aed32de8142767686

import { createContext } from "clean-di/runtime";
import { MainLogger } from "./MainLogger";
import { BackupLogger } from "./BackupLogger";
import { UseCase } from "./UseCase";

export const appContext = createContext<AppConfig, { useCase: unknown }>(
  (cfg) => {
    const mode = cfg.mode;
    const mainLogger = new MainLogger();
    const backupLogger = new BackupLogger();
    const useCase = new UseCase(mainLogger);

    return {
      bag: { mode, mainLogger, backupLogger, useCase },
      expose: { useCase },
    };
  },
);
