// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.
// Source: input.di.ts
// Generator: clean-di-codegen 1.0.0
// Hash: sha256:55b5c479809ff86d79d45c34a0fdb9bb6d085b648d2bc457740c9bc08c3fc1ad

import { createContext } from "clean-di/runtime";
import { BackupLogger } from "./BackupLogger";
import { MainLogger } from "./MainLogger";
import { UseCase } from "./UseCase";

export const appContext = createContext<AppConfig, { useCase: UseCase }>(
  (cfg) => {
    const mode = cfg.mode;
    const mainLogger = new MainLogger();
    const backupLogger = new BackupLogger();
    const useCase = new UseCase(mainLogger);

    return {
      bag: { mode, mainLogger, backupLogger, useCase },
      expose: { useCase },
    };
  },
);
