import { copyFile, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";
import ts from "typescript";

import { DiagnosticReporter } from "../../src/diagnostics/report";
import { emitGeneratedFile } from "../../src/emitter/emitGeneratedFile";

const FIXTURES = join(__dirname, "..", "fixtures", "unambiguous");
const LIFECYCLE_FIXTURES = join(__dirname, "..", "fixtures", "lifecycle");
const CONFIG_BEAN_FIXTURES = join(__dirname, "..", "fixtures", "config-bean-direct");
const IMPORTS_LIFECYCLE_FIXTURES = join(__dirname, "..", "fixtures", "imports-with-lifecycle");

async function stubCleanDi(root: string): Promise<void> {
  const cleanDiDir = join(root, "node_modules", "clean-di", "src", "public");
  await mkdir(cleanDiDir, { recursive: true });

  // Type-preserving stubs so the type checker sees realistic types during
  // analysis. In particular, `provide<T>(factory): T` preserves the return
  // type — without this, `provide((cfg) => cfg.x)` would yield `any`, which
  // is assignable to every parameter and breaks ambiguity tracking.
  await writeFile(
    join(cleanDiDir, "defineContext.ts"),
    `export function defineContext<TConfig = void>(): (spec: any) => any { return () => undefined as any; }`,
  );
  await writeFile(
    join(cleanDiDir, "defineConfig.ts"),
    `export function defineConfig<T>(spec: T): T { return spec; }`,
  );
  await writeFile(
    join(cleanDiDir, "bean.ts"),
    `export function bean<C extends new (...args: any[]) => any>(Class: C, overrides?: any): InstanceType<C> { return undefined as any; }`,
  );
  await writeFile(
    join(cleanDiDir, "provide.ts"),
    `export function provide<T>(factory: (cfg: any) => T): T { return undefined as any; }`,
  );
  await writeFile(
    join(cleanDiDir, "index.ts"),
    [
      `export { defineContext } from "./defineContext";`,
      `export { defineConfig } from "./defineConfig";`,
      `export { bean } from "./bean";`,
      `export { provide } from "./provide";`,
    ].join("\n"),
  );
  await writeFile(
    join(root, "node_modules", "clean-di", "package.json"),
    JSON.stringify({
      name: "clean-di",
      main: "./src/public/index.ts",
      types: "./src/public/index.ts",
      exports: { ".": "./src/public/index.ts" },
    }),
  );
}

async function copyFixture(src: string, dst: string): Promise<void> {
  await copyFile(src, dst);
}

describe("emitGeneratedFile() — MVP integration", () => {
  let workDir: string;

  beforeEach(async () => {
    workDir = join(tmpdir(), `clean-di-emit-test-${Date.now()}-${Math.random()}`);
    await mkdir(workDir, { recursive: true });
    await stubCleanDi(workDir);

    // Copy the unambiguous fixture into the workDir so the codegen can write
    // a sibling `.di.generated.ts` without polluting the fixtures dir.
    for (const file of [
      "input.di.ts",
      "Logger.ts",
      "HttpPostsRepository.ts",
      "ListPostsUseCase.ts",
    ]) {
      await copyFixture(join(FIXTURES, file), join(workDir, file));
    }
  });

  afterEach(async () => {
    await rm(workDir, { recursive: true, force: true });
  });

  it("emits a well-formed .di.generated.ts for the unambiguous fixture", async () => {
    const sourcePath = join(workDir, "input.di.ts");
    const program = ts.createProgram({
      rootNames: [sourcePath],
      options: {
        target: ts.ScriptTarget.ES2022,
        module: ts.ModuleKind.NodeNext,
        moduleResolution: ts.ModuleResolutionKind.NodeNext,
        strict: false,
        noEmit: true,
        allowJs: false,
        skipLibCheck: true,
        esModuleInterop: true,
        baseUrl: workDir,
      },
    });

    const reporter = new DiagnosticReporter(() => {}, false);
    const result = await emitGeneratedFile({
      sourcePath,
      program,
      reporter,
      generatorVersion: "1.0.0",
    });

    expect(result.wrote).toBe(true);
    expect(result.diagnostics).toHaveLength(0);
    expect(reporter.hasErrors()).toBe(false);

    const generated = await readFile(result.outputPath, "utf8");

    // Structural assertions — the emitted file must contain these key elements.
    expect(generated).toContain("AUTO-GENERATED by clean-di-codegen");
    expect(generated).toContain(`import { createContext } from "clean-di/runtime";`);
    expect(generated).toContain(`import { Logger } from "./Logger";`);
    expect(generated).toContain(`import { HttpPostsRepository } from "./HttpPostsRepository";`);
    expect(generated).toContain(`import { ListPostsUseCase } from "./ListPostsUseCase";`);
    expect(generated).toContain(`export const postsContext = createContext<PostsContextConfig`);
    expect(generated).toContain("const apiBaseUrl = cfg.apiBaseUrl");
    expect(generated).toContain("const logger = new Logger()");
    expect(generated).toContain(
      "const postsRepository = new HttpPostsRepository(apiBaseUrl, logger)",
    );
    expect(generated).toContain("const listPosts = new ListPostsUseCase(postsRepository)");
    expect(generated).toContain("expose: { listPosts }");
  });

  it("emits beans in dependency order (Logger before Repository before UseCase)", async () => {
    const sourcePath = join(workDir, "input.di.ts");
    const program = ts.createProgram({
      rootNames: [sourcePath],
      options: {
        target: ts.ScriptTarget.ES2022,
        module: ts.ModuleKind.NodeNext,
        moduleResolution: ts.ModuleResolutionKind.NodeNext,
        strict: false,
        noEmit: true,
        skipLibCheck: true,
        esModuleInterop: true,
        baseUrl: workDir,
      },
    });

    const reporter = new DiagnosticReporter(() => {}, false);
    const result = await emitGeneratedFile({
      sourcePath,
      program,
      reporter,
      generatorVersion: "1.0.0",
    });

    expect(result.wrote).toBe(true);
    const generated = await readFile(result.outputPath, "utf8");

    const loggerIdx = generated.indexOf("const logger ");
    const repoIdx = generated.indexOf("const postsRepository ");
    const useCaseIdx = generated.indexOf("const listPosts ");
    expect(loggerIdx).toBeLessThan(repoIdx);
    expect(repoIdx).toBeLessThan(useCaseIdx);
  });

  it("skips writing when the hash matches an existing generated file", async () => {
    const sourcePath = join(workDir, "input.di.ts");

    function buildProgram(): ts.Program {
      return ts.createProgram({
        rootNames: [sourcePath],
        options: {
          target: ts.ScriptTarget.ES2022,
          module: ts.ModuleKind.NodeNext,
          moduleResolution: ts.ModuleResolutionKind.NodeNext,
          strict: false,
          noEmit: true,
          skipLibCheck: true,
          esModuleInterop: true,
          baseUrl: workDir,
        },
      });
    }

    const reporter = new DiagnosticReporter(() => {}, false);

    const first = await emitGeneratedFile({
      sourcePath,
      program: buildProgram(),
      reporter,
      generatorVersion: "1.0.0",
    });
    expect(first.wrote).toBe(true);

    const second = await emitGeneratedFile({
      sourcePath,
      program: buildProgram(),
      reporter,
      generatorVersion: "1.0.0",
    });
    expect(second.wrote).toBe(false);
    expect(second.diagnostics).toHaveLength(0);
  });

  it("emits postConstruct and preDestroy hooks when present in the spec", async () => {
    // Copy the lifecycle fixture into the workDir alongside the unambiguous
    // files already there. The codegen will write the generated file adjacent
    // to `input.di.ts`, so we overwrite `input.di.ts` with the lifecycle one.
    for (const file of ["input.di.ts", "Logger.ts", "Greeter.ts"]) {
      await copyFile(join(LIFECYCLE_FIXTURES, file), join(workDir, file));
    }

    const sourcePath = join(workDir, "input.di.ts");
    const program = ts.createProgram({
      rootNames: [sourcePath],
      options: {
        target: ts.ScriptTarget.ES2022,
        module: ts.ModuleKind.NodeNext,
        moduleResolution: ts.ModuleResolutionKind.NodeNext,
        strict: false,
        noEmit: true,
        skipLibCheck: true,
        esModuleInterop: true,
        baseUrl: workDir,
      },
    });

    const reporter = new DiagnosticReporter(() => {}, false);
    const result = await emitGeneratedFile({
      sourcePath,
      program,
      reporter,
      generatorVersion: "1.0.0",
    });

    expect(result.wrote).toBe(true);
    expect(result.diagnostics).toHaveLength(0);

    const generated = await readFile(result.outputPath, "utf8");

    // Adapter pattern: user's hook `(beans, cfg) => ...` is wrapped in a
    // `(cfg) => ...` lambda that supplies the locally-built bean bag.
    expect(generated).toContain("postConstruct: (cfg) => (");
    expect(generated).toContain("preDestroy: (cfg) => (");
    // The user's hook source is emitted verbatim inside the adapter.
    expect(generated).toContain("greeter.init()");
    expect(generated).toContain("greeter.dispose()");
    // The hooks have 1 parameter (no cfg), so the bag is passed without cfg.
    expect(generated).toContain("({ logger, greeter })");
  });

  it("re-emits when the generator version changes (hash mismatch)", async () => {
    const sourcePath = join(workDir, "input.di.ts");

    function buildProgram(): ts.Program {
      return ts.createProgram({
        rootNames: [sourcePath],
        options: {
          target: ts.ScriptTarget.ES2022,
          module: ts.ModuleKind.NodeNext,
          moduleResolution: ts.ModuleResolutionKind.NodeNext,
          strict: false,
          noEmit: true,
          skipLibCheck: true,
          esModuleInterop: true,
          baseUrl: workDir,
        },
      });
    }

    const reporter = new DiagnosticReporter(() => {}, false);
    await emitGeneratedFile({
      sourcePath,
      program: buildProgram(),
      reporter,
      generatorVersion: "1.0.0",
    });

    const second = await emitGeneratedFile({
      sourcePath,
      program: buildProgram(),
      reporter,
      generatorVersion: "2.0.0",
    });
    expect(second.wrote).toBe(true);
  });

  it("emits cfg.<name> for a constructor param resolved from a synthetic config scope entry (P0-A)", async () => {
    // The config-bean-direct fixture has NO explicit provide() for `prefix`.
    // The resolver matches Greeter's `prefix: string` against the synthetic
    // config bean (kind: "config"), so the emitter must emit `cfg.prefix`,
    // not `new unknown()`.
    for (const file of ["input.di.ts", "Logger.ts", "Greeter.ts"]) {
      await copyFile(join(CONFIG_BEAN_FIXTURES, file), join(workDir, file));
    }

    const sourcePath = join(workDir, "input.di.ts");
    const program = ts.createProgram({
      rootNames: [sourcePath],
      options: {
        target: ts.ScriptTarget.ES2022,
        module: ts.ModuleKind.NodeNext,
        moduleResolution: ts.ModuleResolutionKind.NodeNext,
        strict: false,
        noEmit: true,
        skipLibCheck: true,
        esModuleInterop: true,
        baseUrl: workDir,
      },
    });

    const reporter = new DiagnosticReporter(() => {}, false);
    const result = await emitGeneratedFile({ sourcePath, program, reporter, generatorVersion: "1.0.0" });

    expect(result.wrote).toBe(true);
    expect(result.diagnostics).toHaveLength(0);
    expect(reporter.hasErrors()).toBe(false);

    const generated = await readFile(result.outputPath, "utf8");
    expect(generated).toContain("const prefix = cfg.prefix");
    expect(generated).toContain("const greeter = new Greeter(prefix, logger)");
    expect(generated).not.toContain("new unknown()");
  });

  it("aggregates lifecycle hooks from imported defineConfig in DESIGN §5.6 order (P0-B)", async () => {
    // The imports-with-lifecycle fixture has helperConfig with postConstruct/preDestroy,
    // and appContext that imports helperConfig and adds its own hooks.
    // Expected postConstruct order: helper THEN app (imports-first).
    // Expected preDestroy order: app THEN helper (parent-first, LIFO).
    for (const file of ["input.di.ts", "Logger.ts", "Greeter.ts", "helperConfig.ts"]) {
      await copyFile(join(IMPORTS_LIFECYCLE_FIXTURES, file), join(workDir, file));
    }

    const sourcePath = join(workDir, "input.di.ts");
    const program = ts.createProgram({
      rootNames: [sourcePath],
      options: {
        target: ts.ScriptTarget.ES2022,
        module: ts.ModuleKind.NodeNext,
        moduleResolution: ts.ModuleResolutionKind.NodeNext,
        strict: false,
        noEmit: true,
        skipLibCheck: true,
        esModuleInterop: true,
        baseUrl: workDir,
      },
    });

    const reporter = new DiagnosticReporter(() => {}, false);
    const result = await emitGeneratedFile({ sourcePath, program, reporter, generatorVersion: "1.0.0" });

    expect(result.wrote).toBe(true);
    expect(result.diagnostics).toHaveLength(0);
    expect(reporter.hasErrors()).toBe(false);

    const generated = await readFile(result.outputPath, "utf8");

    // Block form (2 hooks each): both helperConfig and appContext hooks present.
    expect(generated).toContain("postConstruct: (cfg) => {");
    expect(generated).toContain("preDestroy: (cfg) => {");

    // postConstruct: imported hook appears BEFORE the parent hook.
    const helperPostIdx = generated.indexOf("helper:postConstruct");
    const appPostIdx = generated.indexOf("greeter.greet");
    expect(helperPostIdx).toBeGreaterThan(-1);
    expect(appPostIdx).toBeGreaterThan(-1);
    expect(helperPostIdx).toBeLessThan(appPostIdx);

    // preDestroy: parent hook appears BEFORE the imported hook.
    const appDestroyIdx = generated.indexOf("app:preDestroy");
    const helperDestroyIdx = generated.indexOf("helper:preDestroy");
    expect(appDestroyIdx).toBeGreaterThan(-1);
    expect(helperDestroyIdx).toBeGreaterThan(-1);
    expect(appDestroyIdx).toBeLessThan(helperDestroyIdx);
  });
});
