import { copyFile, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";
import ts from "typescript";

import { DiagnosticReporter } from "../../src/diagnostics/report";
import { emitGeneratedFile } from "../../src/emitter/emitGeneratedFile";

const FIXTURES = join(__dirname, "..", "fixtures", "unambiguous");

async function stubCleanDi(root: string): Promise<void> {
  const cleanDiDir = join(root, "node_modules", "clean-di", "src", "public");
  await mkdir(cleanDiDir, { recursive: true });

  for (const fn of ["defineContext", "defineConfig", "bean", "provide"]) {
    await writeFile(
      join(cleanDiDir, `${fn}.ts`),
      `export function ${fn}(...args: any[]): any { return args; }`,
    );
  }
  await writeFile(
    join(cleanDiDir, "index.ts"),
    [
      `export { defineContext } from "./defineContext";`,
      `export { defineConfig } from "./defineConfig";`,
      `export { bean } from "./bean";`,
      `export { provide } from "./provide";`,
    ].join("\n"),
  );
  await writeFile(
    join(root, "node_modules", "clean-di", "package.json"),
    JSON.stringify({
      name: "clean-di",
      main: "./src/public/index.ts",
      types: "./src/public/index.ts",
      exports: { ".": "./src/public/index.ts" },
    }),
  );
}

async function copyFixture(src: string, dst: string): Promise<void> {
  await copyFile(src, dst);
}

describe("emitGeneratedFile() — MVP integration", () => {
  let workDir: string;

  beforeEach(async () => {
    workDir = join(tmpdir(), `clean-di-emit-test-${Date.now()}-${Math.random()}`);
    await mkdir(workDir, { recursive: true });
    await stubCleanDi(workDir);

    // Copy the unambiguous fixture into the workDir so the codegen can write
    // a sibling `.di.generated.ts` without polluting the fixtures dir.
    for (const file of [
      "input.di.ts",
      "Logger.ts",
      "HttpPostsRepository.ts",
      "ListPostsUseCase.ts",
    ]) {
      await copyFixture(join(FIXTURES, file), join(workDir, file));
    }
  });

  afterEach(async () => {
    await rm(workDir, { recursive: true, force: true });
  });

  it("emits a well-formed .di.generated.ts for the unambiguous fixture", async () => {
    const sourcePath = join(workDir, "input.di.ts");
    const program = ts.createProgram({
      rootNames: [sourcePath],
      options: {
        target: ts.ScriptTarget.ES2022,
        module: ts.ModuleKind.NodeNext,
        moduleResolution: ts.ModuleResolutionKind.NodeNext,
        strict: false,
        noEmit: true,
        allowJs: false,
        skipLibCheck: true,
        esModuleInterop: true,
        baseUrl: workDir,
      },
    });

    const reporter = new DiagnosticReporter(() => {}, false);
    const result = await emitGeneratedFile({
      sourcePath,
      program,
      reporter,
      generatorVersion: "1.0.0",
    });

    expect(result.wrote).toBe(true);
    expect(result.diagnostics).toHaveLength(0);
    expect(reporter.hasErrors()).toBe(false);

    const generated = await readFile(result.outputPath, "utf8");

    // Structural assertions — the emitted file must contain these key elements.
    expect(generated).toContain("AUTO-GENERATED by clean-di-codegen");
    expect(generated).toContain(`import { createContext } from "clean-di/runtime";`);
    expect(generated).toContain(`import { Logger } from "./Logger";`);
    expect(generated).toContain(`import { HttpPostsRepository } from "./HttpPostsRepository";`);
    expect(generated).toContain(`import { ListPostsUseCase } from "./ListPostsUseCase";`);
    expect(generated).toContain(`export const postsContext = createContext<PostsContextConfig`);
    expect(generated).toContain("const apiBaseUrl = cfg.apiBaseUrl");
    expect(generated).toContain("const logger = new Logger()");
    expect(generated).toContain(
      "const postsRepository = new HttpPostsRepository(apiBaseUrl, logger)",
    );
    expect(generated).toContain("const listPosts = new ListPostsUseCase(postsRepository)");
    expect(generated).toContain("expose: { listPosts }");
  });

  it("emits beans in dependency order (Logger before Repository before UseCase)", async () => {
    const sourcePath = join(workDir, "input.di.ts");
    const program = ts.createProgram({
      rootNames: [sourcePath],
      options: {
        target: ts.ScriptTarget.ES2022,
        module: ts.ModuleKind.NodeNext,
        moduleResolution: ts.ModuleResolutionKind.NodeNext,
        strict: false,
        noEmit: true,
        skipLibCheck: true,
        esModuleInterop: true,
        baseUrl: workDir,
      },
    });

    const reporter = new DiagnosticReporter(() => {}, false);
    const result = await emitGeneratedFile({
      sourcePath,
      program,
      reporter,
      generatorVersion: "1.0.0",
    });

    expect(result.wrote).toBe(true);
    const generated = await readFile(result.outputPath, "utf8");

    const loggerIdx = generated.indexOf("const logger ");
    const repoIdx = generated.indexOf("const postsRepository ");
    const useCaseIdx = generated.indexOf("const listPosts ");
    expect(loggerIdx).toBeLessThan(repoIdx);
    expect(repoIdx).toBeLessThan(useCaseIdx);
  });

  it("skips writing when the hash matches an existing generated file", async () => {
    const sourcePath = join(workDir, "input.di.ts");

    function buildProgram(): ts.Program {
      return ts.createProgram({
        rootNames: [sourcePath],
        options: {
          target: ts.ScriptTarget.ES2022,
          module: ts.ModuleKind.NodeNext,
          moduleResolution: ts.ModuleResolutionKind.NodeNext,
          strict: false,
          noEmit: true,
          skipLibCheck: true,
          esModuleInterop: true,
          baseUrl: workDir,
        },
      });
    }

    const reporter = new DiagnosticReporter(() => {}, false);

    const first = await emitGeneratedFile({
      sourcePath,
      program: buildProgram(),
      reporter,
      generatorVersion: "1.0.0",
    });
    expect(first.wrote).toBe(true);

    const second = await emitGeneratedFile({
      sourcePath,
      program: buildProgram(),
      reporter,
      generatorVersion: "1.0.0",
    });
    expect(second.wrote).toBe(false);
    expect(second.diagnostics).toHaveLength(0);
  });

  it("re-emits when the generator version changes (hash mismatch)", async () => {
    const sourcePath = join(workDir, "input.di.ts");

    function buildProgram(): ts.Program {
      return ts.createProgram({
        rootNames: [sourcePath],
        options: {
          target: ts.ScriptTarget.ES2022,
          module: ts.ModuleKind.NodeNext,
          moduleResolution: ts.ModuleResolutionKind.NodeNext,
          strict: false,
          noEmit: true,
          skipLibCheck: true,
          esModuleInterop: true,
          baseUrl: workDir,
        },
      });
    }

    const reporter = new DiagnosticReporter(() => {}, false);
    await emitGeneratedFile({
      sourcePath,
      program: buildProgram(),
      reporter,
      generatorVersion: "1.0.0",
    });

    const second = await emitGeneratedFile({
      sourcePath,
      program: buildProgram(),
      reporter,
      generatorVersion: "2.0.0",
    });
    expect(second.wrote).toBe(true);
  });
});
