import { describe, expect, it } from "vitest";

import { formatGenerated, type FormatGeneratedInput } from "../../src/emitter/formatGenerated";

const baseInput: FormatGeneratedInput = {
  sourcePath: "src/blog/posts/PostsContext.di.ts",
  generatorVersion: "1.0.0",
  hash: "a3f8c9d2",
  imports: [
    { from: "./Logger", named: [{ name: "Logger" }] },
    { from: "./HttpPostsRepository", named: [{ name: "HttpPostsRepository" }] },
    { from: "./ListPostsUseCase", named: [{ name: "ListPostsUseCase" }] },
    { from: "clean-di/runtime", named: [{ name: "createContext" }] },
    {
      from: "./PostsContext.di",
      named: [{ name: "PostsContextConfig", typeOnly: true }],
    },
  ],
  configTypeName: "PostsContextConfig",
  contextExportName: "postsContext",
  beansInTopoOrder: [
    { name: "apiBaseUrl", rhs: "cfg.apiBaseUrl" },
    { name: "authToken", rhs: "cfg.authToken" },
    { name: "logger", rhs: `new Logger("posts")` },
    { name: "postsRepository", rhs: "new HttpPostsRepository(apiBaseUrl, authToken, logger)" },
    { name: "listPosts", rhs: "new ListPostsUseCase(postsRepository)" },
  ],
  exposedKeys: ["listPosts"],
  exposedTypes: new Map([["listPosts", "ListPostsUseCase"]]),
  headerTemplate: [
    "// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.",
    "// Source: {source}",
    "// Generator: {generator}",
    "// Hash: {hash}",
  ].join("\n"),
  postConstructSources: [],
  preDestroySources: [],
};

describe("formatGenerated()", () => {
  it("renders a valid generated-file shell that includes header, imports, and createContext call", () => {
    const out = formatGenerated(baseInput);

    expect(out).toContain("AUTO-GENERATED by clean-di-codegen");
    expect(out).toContain("Source: src/blog/posts/PostsContext.di.ts");
    expect(out).toContain("Generator: clean-di-codegen 1.0.0");
    expect(out).toContain("Hash: sha256:a3f8c9d2");
    expect(out).toContain(`import { createContext } from "clean-di/runtime";`);
    expect(out).toContain(`export const postsContext = createContext<PostsContextConfig,`);
  });

  it("emits beans in the supplied topological order", () => {
    const out = formatGenerated(baseInput);

    const apiIdx = out.indexOf("const apiBaseUrl");
    const repoIdx = out.indexOf("const postsRepository");
    const useCaseIdx = out.indexOf("const listPosts");

    expect(apiIdx).toBeLessThan(repoIdx);
    expect(repoIdx).toBeLessThan(useCaseIdx);
  });

  it("emits the bag with every bean name and expose with whitelisted keys", () => {
    const out = formatGenerated(baseInput);
    expect(out).toContain("bag: { apiBaseUrl, authToken, logger, postsRepository, listPosts }");
    expect(out).toContain("expose: { listPosts }");
  });

  it("emits type-only named imports with `type` prefix", () => {
    const out = formatGenerated(baseInput);
    expect(out).toContain(`import { type PostsContextConfig } from "./PostsContext.di";`);
  });

  it("emits aliased named imports", () => {
    const out = formatGenerated({
      ...baseInput,
      imports: [
        ...baseInput.imports,
        {
          from: "./shared",
          named: [{ name: "Helper", alias: "ShareHelper" }],
        },
      ],
    });
    expect(out).toContain(`import { Helper as ShareHelper } from "./shared";`);
  });

  it("emits empty exposed type as {} when no expose keys", () => {
    const out = formatGenerated({ ...baseInput, exposedKeys: [] });
    expect(out).toContain(`createContext<PostsContextConfig, {}>`);
  });

  it("emits postConstruct field when a single postConstructSource is provided", () => {
    const out = formatGenerated({
      ...baseInput,
      postConstructSources: [
        { src: "({ logger }, cfg) => { logger.info(cfg.apiBaseUrl); }", passCfg: true },
      ],
    });

    // Single hook → inline expression form, cfg passed because passCfg = true.
    expect(out).toContain(
      "postConstruct: (cfg) => (({ logger }, cfg) => { logger.info(cfg.apiBaseUrl); })({ apiBaseUrl, authToken, logger, postsRepository, listPosts }, cfg),",
    );
    expect(out).not.toContain("preDestroy:");
  });

  it("emits preDestroy field when a single preDestroySource is provided", () => {
    const out = formatGenerated({
      ...baseInput,
      preDestroySources: [{ src: "({ logger }) => { logger.info('bye'); }", passCfg: false }],
    });

    // Single hook → no cfg argument because passCfg = false.
    expect(out).toContain(
      "preDestroy: (cfg) => (({ logger }) => { logger.info('bye'); })({ apiBaseUrl, authToken, logger, postsRepository, listPosts }),",
    );
    expect(out).not.toContain("postConstruct:");
  });

  it("emits block-form postConstruct when multiple postConstructSources are provided", () => {
    const out = formatGenerated({
      ...baseInput,
      postConstructSources: [
        { src: "({ logger }) => { logger.info('imported init'); }", passCfg: false },
        { src: "({ logger }, cfg) => { logger.info(cfg.apiBaseUrl); }", passCfg: true },
      ],
    });

    // Block form wraps all hooks in a block arrow.
    expect(out).toContain("postConstruct: (cfg) => {");
    expect(out).toContain(
      "(({ logger }) => { logger.info('imported init'); })({ apiBaseUrl, authToken, logger, postsRepository, listPosts });",
    );
    expect(out).toContain(
      "(({ logger }, cfg) => { logger.info(cfg.apiBaseUrl); })({ apiBaseUrl, authToken, logger, postsRepository, listPosts }, cfg);",
    );
    expect(out).not.toContain("preDestroy:");
  });

  it("emits block-form preDestroy when multiple preDestroySources are provided", () => {
    const out = formatGenerated({
      ...baseInput,
      preDestroySources: [
        { src: "({ logger }) => { logger.info('first destroy'); }", passCfg: false },
        { src: "({ logger }) => { logger.info('second destroy'); }", passCfg: false },
      ],
    });

    expect(out).toContain("preDestroy: (cfg) => {");
    expect(out).toContain(
      "(({ logger }) => { logger.info('first destroy'); })({ apiBaseUrl, authToken, logger, postsRepository, listPosts });",
    );
    expect(out).toContain(
      "(({ logger }) => { logger.info('second destroy'); })({ apiBaseUrl, authToken, logger, postsRepository, listPosts });",
    );
  });

  it("emits neither postConstruct nor preDestroy when both arrays are empty", () => {
    const out = formatGenerated(baseInput);

    expect(out).not.toContain("postConstruct:");
    expect(out).not.toContain("preDestroy:");
  });
});
