/**
 * Default codegen configuration. The user's `clean-di.config.ts` (resolved by
 * `loadConfig`) is shallow-merged over this; `include` and `exclude` arrays
 * concatenate rather than replace.
 *
 * See DESIGN.md §7.2 for the resolution algorithm.
 */

/**
 * Output mode. `adjacent` is the only mode supported in v1 (writes
 * `*.di.generated.ts` next to the source `*.di.ts`). Other values are reserved
 * for forward compatibility; the codegen throws if it sees them.
 */
export type OutputMode = "adjacent";

/**
 * User-facing codegen configuration shape. All fields are optional in the
 * user's config file; missing values fall back to `defaultConfig`.
 */
export interface CleanDiConfig {
  readonly include?: readonly string[];
  readonly exclude?: readonly string[];
  readonly tsconfig?: string;
  readonly output?: OutputMode;
  readonly header?: string;
}

/**
 * Fully-resolved configuration (the merged shape used downstream). Required
 * counterparts of every CleanDiConfig field.
 */
export interface ResolvedCleanDiConfig {
  readonly include: readonly string[];
  readonly exclude: readonly string[];
  readonly tsconfig: string;
  readonly output: OutputMode;
  readonly header: string;
}

/**
 * Default header text written at the top of every `.di.generated.ts` file.
 * Mirrors DESIGN §7.8 example. `{source}`, `{generator}`, `{hash}` placeholders
 * are substituted by the emitter at write time.
 */
export const DEFAULT_HEADER: string = [
  "// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.",
  "// Source: {source}",
  "// Generator: {generator}",
  "// Hash: {hash}",
].join("\n");

export const defaultConfig: ResolvedCleanDiConfig = {
  include: ["src/**/*.di.ts"],
  exclude: ["**/node_modules/**", "**/*.test.ts"],
  tsconfig: "./tsconfig.json",
  output: "adjacent",
  header: DEFAULT_HEADER,
};
