// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.
// Source: BlogContext.di.ts
// Generator: clean-di-codegen 1.0.0
// Hash: sha256:3d85db2d0c34d6a657fdc42a2ff25b2822adfd66aba020dec070fde9f3a190ca

import { createContext } from "clean-di/runtime";
import { Logger } from "../shared/Logger.js";
import { type BlogConfig } from "./BlogConfig.js";
import { commentsConfig } from "./comments/CommentsConfig.di.js";
import { CreatePostUseCase } from "./posts/CreatePostUseCase.js";
import { HttpPostsRepository } from "./posts/HttpPostsRepository.js";
import { ListPostsUseCase } from "./posts/ListPostsUseCase.js";
import { usersConfig } from "./users/UsersConfig.di.js";
import { HttpCommentsRepository } from "./comments/HttpCommentsRepository.js";
import { ListCommentsUseCase } from "./comments/ListCommentsUseCase.js";
import { DeleteCommentUseCase } from "./comments/DeleteCommentUseCase.js";
import { HttpUsersRepository } from "./users/HttpUsersRepository.js";
import { GetCurrentUserUseCase } from "./users/GetCurrentUserUseCase.js";

export const blogContext = createContext<BlogConfig, { listPosts: ListPostsUseCase, createPost: CreatePostUseCase, listComments: ListCommentsUseCase, deleteComment: DeleteCommentUseCase, getCurrentUser: GetCurrentUserUseCase }>(
  (cfg) => {
    const apiBaseUrl = cfg.apiBaseUrl;
    const authToken = cfg.authToken;
    const logger = new Logger("blog");
    const commentsRepository = new HttpCommentsRepository(apiBaseUrl, authToken, logger);
    const listComments = new ListCommentsUseCase(commentsRepository);
    const deleteComment = new DeleteCommentUseCase(commentsRepository);
    const usersRepository = new HttpUsersRepository(apiBaseUrl, authToken, logger);
    const getCurrentUser = new GetCurrentUserUseCase(usersRepository);
    const postsRepository = new HttpPostsRepository(apiBaseUrl, authToken, logger);
    const listPosts = new ListPostsUseCase(postsRepository);
    const createPost = new CreatePostUseCase(postsRepository);

    return {
      bag: { apiBaseUrl, authToken, logger, commentsRepository, listComments, deleteComment, usersRepository, getCurrentUser, postsRepository, listPosts, createPost },
      expose: { listPosts, createPost, listComments, deleteComment, getCurrentUser },
      postConstruct: (cfg) => (({ logger }, cfg) => logger.info(`blog ready — ${cfg.apiBaseUrl}`))({ apiBaseUrl, authToken, logger, commentsRepository, listComments, deleteComment, usersRepository, getCurrentUser, postsRepository, listPosts, createPost }, cfg),
      preDestroy: (cfg) => (({ logger }, _cfg) => logger.info("blog destroyed"))({ apiBaseUrl, authToken, logger, commentsRepository, listComments, deleteComment, usersRepository, getCurrentUser, postsRepository, listPosts, createPost }, cfg),
    };
  },
);
