// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.
// Source: input.di.ts
// Generator: clean-di-codegen 1.0.0
// Hash: sha256:40df5eacdcfc7522189bd61cdceb8f75d345fb1f868f305f8230a54589b097c7

import { createContext } from "clean-di/runtime";
import { Logger } from "./Logger";
import { ServiceA } from "./ServiceA";
import { ServiceB } from "./ServiceB";

export const contextB = createContext<void, { serviceB: ServiceB }>(
  (cfg) => {
    const logger = new Logger();
    const serviceB = new ServiceB(logger);

    return {
      bag: { logger, serviceB },
      expose: { serviceB },
    };
  },
);
