// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.
// Source: input.di.ts
// Generator: clean-di-codegen 1.0.0
// Hash: sha256:7597cea04cc08ea085553d78973c1b3b57311652461f1fe873eea3afbe6bd91a

import { createContext } from "clean-di/runtime";
import { Logger } from "./Logger";
import { ServiceA } from "./ServiceA";
import { ServiceB } from "./ServiceB";

export const contextA = createContext<void, { serviceA: ServiceA }>(
  (cfg) => {
    const logger = new Logger();
    const serviceA = new ServiceA(logger);

    return {
      bag: { logger, serviceA },
      expose: { serviceA },
    };
  },
);
