// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.
// Source: input.di.ts
// Generator: clean-di-codegen 1.0.0
// Hash: sha256:09e13df976a7d51a98334120335a9ef2f201002bc219439269ced6ef24636b63

import { createContext } from "clean-di/runtime";
import { Logger } from "./Logger";
import { BackupLogger } from "./BackupLogger";
import { UseCase } from "./UseCase";

export const appContext = createContext<void, { useCase: UseCase }>(
  (cfg) => {
    const logger = new Logger();
    const backupLogger = new BackupLogger();
    const useCase = new UseCase(logger);

    return {
      bag: { logger, backupLogger, useCase },
      expose: { useCase },
    };
  },
);
