// AUTO-GENERATED by clean-di-codegen — DO NOT EDIT.
// Source: input.di.ts
// Generator: clean-di-codegen 1.0.0
// Hash: sha256:ee2de9476b5ef37daf037c3d4371baaa33786771a8a6737bd3b801694f65a2ae

import { createContext } from "clean-di/runtime";
import { BackupLogger } from "./BackupLogger";
import { Logger } from "./Logger";
import { UseCase } from "./UseCase";

export const appContext = createContext<void, { useCase: UseCase }>((cfg) => {
  const logger = new Logger();
  const backupLogger = new BackupLogger();
  const useCase = new UseCase(logger);

  return {
    bag: { logger, backupLogger, useCase },
    expose: { useCase },
  };
});
